{"filename_spec":"taint-output.json","root":"/home/sampath/mis/fact-bounty/fact-bounty-flask","tool":"pysa","version":"a503d8845a2a27cb046d8233298374eb931006f4","stats":{"skipped_overrides":[],"model_verification_errors":[{"description":"`aiohttp.client.ClientSession.get` is not part of the environment!","line":1,"column":0,"stop_line":9,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.options` is not part of the environment!","line":10,"column":0,"stop_line":18,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.head` is not part of the environment!","line":19,"column":0,"stop_line":27,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.post` is not part of the environment!","line":28,"column":0,"stop_line":35,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.put` is not part of the environment!","line":36,"column":0,"stop_line":43,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.patch` is not part of the environment!","line":44,"column":0,"stop_line":51,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.delete` is not part of the environment!","line":52,"column":0,"stop_line":59,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.ws_connect` is not part of the environment!","line":60,"column":0,"stop_line":80,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.client.ClientSession.request` is not part of the environment!","line":81,"column":0,"stop_line":89,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_client.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.rel_url` is not part of the environment!","line":3,"column":0,"stop_line":3,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.__getitem__` is not part of the environment!","line":4,"column":0,"stop_line":4,"stop_column":117,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.__iter__` is not part of the environment!","line":5,"column":0,"stop_line":5,"stop_column":109,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.forwarded` is not part of the environment!","line":6,"column":0,"stop_line":6,"stop_column":119,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.url` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":109,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.path` is not part of the environment!","line":8,"column":0,"stop_line":8,"stop_column":110,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.path_qs` is not part of the environment!","line":9,"column":0,"stop_line":9,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.raw_path` is not part of the environment!","line":10,"column":0,"stop_line":10,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.query` is not part of the environment!","line":11,"column":0,"stop_line":11,"stop_column":106,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.query_string` is not part of the environment!","line":12,"column":0,"stop_line":12,"stop_column":113,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.headers` is not part of the environment!","line":13,"column":0,"stop_line":13,"stop_column":117,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.raw_headers` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":121,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.cookies` is not part of the environment!","line":15,"column":0,"stop_line":15,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.http_range` is not part of the environment!","line":16,"column":0,"stop_line":16,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.content` is not part of the environment!","line":17,"column":0,"stop_line":17,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.read` is not part of the environment!","line":18,"column":0,"stop_line":18,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.text` is not part of the environment!","line":19,"column":0,"stop_line":19,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.json` is not part of the environment!","line":20,"column":0,"stop_line":20,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.multipart` is not part of the environment!","line":21,"column":0,"stop_line":21,"stop_column":116,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.post` is not part of the environment!","line":22,"column":0,"stop_line":22,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.BaseRequest.__repr__` is not part of the environment!","line":23,"column":0,"stop_line":23,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.Request.match_info` is not part of the environment!","line":25,"column":0,"stop_line":25,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.Request.app` is not part of the environment!","line":26,"column":1,"stop_line":27,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_request.Request.config_dict` is not part of the environment!","line":28,"column":1,"stop_line":29,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_exceptions._HTTPMove.__init__` is not part of the environment!","line":32,"column":0,"stop_line":40,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_exceptions.HTTPException.__init__` is not part of the environment!","line":41,"column":0,"stop_line":48,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_exceptions.HTTPMethodNotAllowed.__init__` is not part of the environment!","line":49,"column":0,"stop_line":58,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_exceptions.HTTPUnavailableForLegalReasons.__init__` is not part of the environment!","line":59,"column":0,"stop_line":67,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.StreamResponse.__init__` is not part of the environment!","line":69,"column":0,"stop_line":75,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.StreamResponse.headers` is not part of the environment!","line":76,"column":1,"stop_line":77,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.StreamResponse.cookies` is not part of the environment!","line":78,"column":1,"stop_line":79,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.StreamResponse.write_eof` is not part of the environment!","line":80,"column":0,"stop_line":80,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.Response.__init__` is not part of the environment!","line":82,"column":0,"stop_line":94,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.Response.body` is not part of the environment!","line":95,"column":1,"stop_line":99,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.Response.text` is not part of the environment!","line":100,"column":1,"stop_line":101,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_response.json_response` is not part of the environment!","line":103,"column":0,"stop_line":113,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.ping` is not part of the environment!","line":115,"column":0,"stop_line":115,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.pong` is not part of the environment!","line":116,"column":0,"stop_line":116,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.send_str` is not part of the environment!","line":117,"column":0,"stop_line":117,"stop_column":96,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.send_bytes` is not part of the environment!","line":118,"column":0,"stop_line":118,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.send_json` is not part of the environment!","line":119,"column":0,"stop_line":119,"stop_column":96,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.close` is not part of the environment!","line":120,"column":0,"stop_line":120,"stop_column":104,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.receive` is not part of the environment!","line":121,"column":0,"stop_line":121,"stop_column":116,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.receive_str` is not part of the environment!","line":122,"column":0,"stop_line":122,"stop_column":121,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.receive_bytes` is not part of the environment!","line":123,"column":0,"stop_line":123,"stop_column":122,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.receive_json` is not part of the environment!","line":124,"column":0,"stop_line":124,"stop_column":121,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.write` is not part of the environment!","line":125,"column":0,"stop_line":125,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.__aiter__` is not part of the environment!","line":126,"column":0,"stop_line":126,"stop_column":88,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`aiohttp.web_ws.WebSocketResponse.__anext__` is not part of the environment!","line":127,"column":0,"stop_line":127,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/aiohttp_server.pysa","code":6},{"description":"`TaintSink[Authentication]` is an invalid taint annotation: Unsupported taint sink `Authentication`","line":2,"column":0,"stop_line":5,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/authentication_sinks.pysa","code":9},{"description":"`boto3.client` is not part of the environment!","line":6,"column":0,"stop_line":12,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/authentication_sinks.pysa","code":6},{"description":"`s3fs.core.S3FileSystem.__init__` is not part of the environment!","line":13,"column":0,"stop_line":17,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/authentication_sinks.pysa","code":6},{"description":"`amazon.api.AmazonAPI.__init__` is not part of the environment!","line":18,"column":0,"stop_line":21,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/authentication_sinks.pysa","code":6},{"description":"`dill._dill.load` is not part of the environment!","line":1,"column":0,"stop_line":1,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/dill_sinks.pysa","code":6},{"description":"`dill._dill.loads` is not part of the environment!","line":2,"column":0,"stop_line":2,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/dill_sinks.pysa","code":6},{"description":"`dill._dill.load_session` is not part of the environment!","line":3,"column":0,"stop_line":3,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/dill_sinks.pysa","code":6},{"description":"`dill._dill.Unpickler.__init__` is not part of the environment!","line":4,"column":0,"stop_line":8,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/dill_sinks.pysa","code":6},{"description":"`rest_framework.request.Request.POST` is not part of the environment!","line":1,"column":1,"stop_line":2,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.FILES` is not part of the environment!","line":3,"column":1,"stop_line":4,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.DATA` is not part of the environment!","line":5,"column":1,"stop_line":6,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.QUERY_PARAMS` is not part of the environment!","line":7,"column":1,"stop_line":8,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.data` is not part of the environment!","line":9,"column":1,"stop_line":10,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.query_params` is not part of the environment!","line":11,"column":1,"stop_line":12,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.content_type` is not part of the environment!","line":13,"column":1,"stop_line":14,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`rest_framework.request.Request.stream` is not part of the environment!","line":15,"column":1,"stop_line":16,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_rest_framework.pysa","code":6},{"description":"`django.http.request.HttpRequest.COOKIES` is not part of the environment!","line":3,"column":0,"stop_line":3,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.META` is not part of the environment!","line":4,"column":0,"stop_line":4,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.user_agent_string` is not part of the environment!","line":5,"column":0,"stop_line":5,"stop_column":105,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.user_agent` is not part of the environment!","line":6,"column":0,"stop_line":6,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.FILES` is not part of the environment!","line":8,"column":0,"stop_line":8,"stop_column":116,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.GET` is not part of the environment!","line":9,"column":0,"stop_line":9,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.POST` is not part of the environment!","line":10,"column":0,"stop_line":10,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.REQUEST` is not part of the environment!","line":11,"column":0,"stop_line":11,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.body` is not part of the environment!","line":12,"column":0,"stop_line":12,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.GET` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":51,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.POST` is not part of the environment!","line":15,"column":0,"stop_line":15,"stop_column":52,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.COOKIES` is not part of the environment!","line":17,"column":0,"stop_line":17,"stop_column":67,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.get_signed_cookie` is not part of the environment!","line":18,"column":0,"stop_line":18,"stop_column":117,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.cookies` is not part of the environment!","line":19,"column":0,"stop_line":19,"stop_column":73,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.META` is not part of the environment!","line":22,"column":0,"stop_line":22,"stop_column":67,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.__repr__` is not part of the environment!","line":23,"column":0,"stop_line":23,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.core.handlers.wsgi.WSGIRequest.environ` is not part of the environment!","line":24,"column":0,"stop_line":24,"stop_column":70,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.build_request_repr` is not part of the environment!","line":25,"column":0,"stop_line":31,"stop_column":33,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.get_full_path` is not part of the environment!","line":33,"column":0,"stop_line":33,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.request.HttpRequest.build_absolute_uri` is not part of the environment!","line":34,"column":0,"stop_line":34,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.__init__` is not part of the environment!","line":42,"column":0,"stop_line":49,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.__init__` is not part of the environment!","line":51,"column":0,"stop_line":56,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.__setitem__` is not part of the environment!","line":58,"column":0,"stop_line":58,"stop_column":162,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.setdefault` is not part of the environment!","line":59,"column":0,"stop_line":59,"stop_column":161,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase._headers` is not part of the environment!","line":62,"column":0,"stop_line":62,"stop_column":71,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase._headers` is not part of the environment!","line":63,"column":0,"stop_line":63,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.serialize_headers` is not part of the environment!","line":64,"column":0,"stop_line":64,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.__bytes__` is not part of the environment!","line":65,"column":0,"stop_line":65,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.items` is not part of the environment!","line":66,"column":0,"stop_line":66,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.get` is not part of the environment!","line":67,"column":0,"stop_line":67,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseBase.__getitem__` is not part of the environment!","line":68,"column":0,"stop_line":68,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.serialize` is not part of the environment!","line":71,"column":0,"stop_line":71,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.__bytes__` is not part of the environment!","line":72,"column":0,"stop_line":72,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.content` is not part of the environment!","line":73,"column":1,"stop_line":74,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.__iter__` is not part of the environment!","line":75,"column":0,"stop_line":75,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.getvalue` is not part of the environment!","line":76,"column":0,"stop_line":76,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponseRedirect.__init__` is not part of the environment!","line":79,"column":0,"stop_line":79,"stop_column":116,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.shortcuts.redirect` is not part of the environment!","line":81,"column":0,"stop_line":81,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.shortcuts.render` is not part of the environment!","line":82,"column":0,"stop_line":82,"stop_column":126,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.shortcuts.render` is not part of the environment!","line":83,"column":0,"stop_line":83,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.core.cache.backends.base.BaseCache.get` is not part of the environment!","line":87,"column":0,"stop_line":87,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.core.cache.backends.base.BaseCache.get_many` is not part of the environment!","line":88,"column":0,"stop_line":88,"stop_column":105,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.core.cache.backends.base.BaseCache.set` is not part of the environment!","line":89,"column":0,"stop_line":89,"stop_column":115,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.core.cache.backends.base.BaseCache.set_many` is not part of the environment!","line":90,"column":0,"stop_line":90,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.db.models.manager.Manager.raw` is not part of the environment!","line":95,"column":0,"stop_line":95,"stop_column":107,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.db.backends.utils.CursorWrapper.execute` is not part of the environment!","line":98,"column":0,"stop_line":98,"stop_column":90,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.db.backends.utils.CursorWrapper.executemany` is not part of the environment!","line":99,"column":0,"stop_line":99,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.db.backends.mysql.base.CursorWrapper.execute` is not part of the environment!","line":100,"column":0,"stop_line":100,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.db.backends.mysql.base.CursorWrapper.executemany` is not part of the environment!","line":101,"column":0,"stop_line":101,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.utils.html.format_html` is not part of the environment!","line":114,"column":0,"stop_line":114,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.utils.html.format_html_join` is not part of the environment!","line":115,"column":0,"stop_line":115,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.http.response.HttpResponse.content` is not part of the environment!","line":122,"column":1,"stop_line":123,"stop_column":79,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.utils.html.escape` is not part of the environment!","line":127,"column":1,"stop_line":128,"stop_column":74,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.utils.html.conditional_escape` is not part of the environment!","line":129,"column":1,"stop_line":130,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.contrib.sessions.backends.base.SessionBase.session_key` is not part of the environment!","line":133,"column":0,"stop_line":133,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.contrib.sessions.backends.base.SessionBase._session_key` is not part of the environment!","line":134,"column":0,"stop_line":134,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`django.db.models.manager.Manager.get` is not part of the environment!","line":137,"column":1,"stop_line":142,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/django_sources_sinks.pysa","code":6},{"description":"`falcon.request.Request.app` is not part of the environment!","line":2,"column":1,"stop_line":3,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.path` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.url` is not part of the environment!","line":10,"column":0,"stop_line":10,"stop_column":90,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.util.uri.decode` is not part of the environment!","line":11,"column":0,"stop_line":11,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.query_string` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.params` is not part of the environment!","line":15,"column":1,"stop_line":16,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request._params` is not part of the environment!","line":17,"column":0,"stop_line":17,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.stream` is not part of the environment!","line":18,"column":0,"stop_line":18,"stop_column":88,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.env` is not part of the environment!","line":19,"column":0,"stop_line":19,"stop_column":67,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.util.uri.parse_query_string` is not part of the environment!","line":20,"column":0,"stop_line":20,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.get_param_as_bool` is not part of the environment!","line":21,"column":1,"stop_line":22,"stop_column":51,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.get_param_as_bool` is not part of the environment!","line":23,"column":1,"stop_line":24,"stop_column":51,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.cookies` is not part of the environment!","line":27,"column":1,"stop_line":28,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request._cookies` is not part of the environment!","line":29,"column":0,"stop_line":29,"stop_column":96,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.forwarded_host` is not part of the environment!","line":33,"column":1,"stop_line":34,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.headers` is not part of the environment!","line":35,"column":1,"stop_line":36,"stop_column":105,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.access_route` is not part of the environment!","line":37,"column":1,"stop_line":38,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.get_header` is not part of the environment!","line":39,"column":0,"stop_line":39,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.user_agent` is not part of the environment!","line":40,"column":0,"stop_line":40,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.referer` is not part of the environment!","line":41,"column":0,"stop_line":41,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.request.Request.auth` is not part of the environment!","line":42,"column":0,"stop_line":42,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response._media` is not part of the environment!","line":45,"column":0,"stop_line":45,"stop_column":69,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response._media` is not part of the environment!","line":46,"column":0,"stop_line":46,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response.body` is not part of the environment!","line":47,"column":0,"stop_line":47,"stop_column":67,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response.body` is not part of the environment!","line":48,"column":0,"stop_line":48,"stop_column":62,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response._data` is not part of the environment!","line":49,"column":0,"stop_line":49,"stop_column":68,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response._data` is not part of the environment!","line":50,"column":0,"stop_line":50,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response.stream` is not part of the environment!","line":51,"column":0,"stop_line":51,"stop_column":69,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response.stream` is not part of the environment!","line":52,"column":0,"stop_line":52,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.response.Response._headers` is not part of the environment!","line":56,"column":0,"stop_line":56,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.redirects.HTTPMovedPermanently.__init__` is not part of the environment!","line":60,"column":0,"stop_line":63,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.redirects.HTTPFound.__init__` is not part of the environment!","line":64,"column":0,"stop_line":67,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.redirects.HTTPSeeOther.__init__` is not part of the environment!","line":68,"column":0,"stop_line":71,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.redirects.HTTPTemporaryRedirect.__init__` is not part of the environment!","line":72,"column":0,"stop_line":75,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`falcon.redirects.HTTPPermanentRedirect.__init__` is not part of the environment!","line":76,"column":0,"stop_line":79,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/falcon_server.pysa","code":6},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":2,"column":0,"stop_line":2,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":3,"column":0,"stop_line":3,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":4,"column":0,"stop_line":4,"stop_column":109,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":5,"column":0,"stop_line":5,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":6,"column":0,"stop_line":6,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":7,"column":0,"stop_line":7,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":8,"column":0,"stop_line":8,"stop_column":69,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":9,"column":0,"stop_line":9,"stop_column":71,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":10,"column":0,"stop_line":10,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":11,"column":0,"stop_line":11,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":12,"column":0,"stop_line":12,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":13,"column":0,"stop_line":13,"stop_column":90,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":14,"column":0,"stop_line":14,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":15,"column":0,"stop_line":15,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":16,"column":0,"stop_line":16,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":17,"column":0,"stop_line":17,"stop_column":62,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":18,"column":0,"stop_line":18,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":19,"column":0,"stop_line":19,"stop_column":186,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":20,"column":0,"stop_line":20,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":21,"column":0,"stop_line":21,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":22,"column":0,"stop_line":22,"stop_column":52,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":23,"column":0,"stop_line":23,"stop_column":53,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":24,"column":0,"stop_line":24,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":25,"column":0,"stop_line":25,"stop_column":57,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":26,"column":0,"stop_line":26,"stop_column":57,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":27,"column":0,"stop_line":27,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":28,"column":0,"stop_line":28,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":29,"column":0,"stop_line":29,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":30,"column":0,"stop_line":30,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":31,"column":0,"stop_line":31,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":32,"column":0,"stop_line":32,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":34,"column":0,"stop_line":34,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":35,"column":0,"stop_line":35,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":36,"column":0,"stop_line":36,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":37,"column":0,"stop_line":37,"stop_column":151,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":38,"column":0,"stop_line":38,"stop_column":69,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":39,"column":0,"stop_line":39,"stop_column":165,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":40,"column":0,"stop_line":40,"stop_column":119,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":42,"column":0,"stop_line":42,"stop_column":146,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":43,"column":0,"stop_line":43,"stop_column":159,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":44,"column":0,"stop_line":44,"stop_column":172,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":45,"column":0,"stop_line":45,"stop_column":153,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":46,"column":0,"stop_line":46,"stop_column":139,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":47,"column":0,"stop_line":47,"stop_column":133,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":48,"column":0,"stop_line":48,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":49,"column":0,"stop_line":49,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":53,"column":0,"stop_line":53,"stop_column":58,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":54,"column":0,"stop_line":54,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":55,"column":0,"stop_line":55,"stop_column":106,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":56,"column":0,"stop_line":56,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":57,"column":0,"stop_line":63,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":64,"column":0,"stop_line":70,"stop_column":8,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":71,"column":0,"stop_line":71,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":73,"column":0,"stop_line":73,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":74,"column":0,"stop_line":74,"stop_column":71,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":76,"column":0,"stop_line":76,"stop_column":68,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":77,"column":0,"stop_line":77,"stop_column":69,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":78,"column":0,"stop_line":78,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":79,"column":0,"stop_line":79,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":80,"column":0,"stop_line":80,"stop_column":101,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":81,"column":0,"stop_line":81,"stop_column":62,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":82,"column":0,"stop_line":82,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":83,"column":0,"stop_line":83,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_other_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_ReadWrite]` is an invalid taint annotation: Unsupported taint sink `FileSystem_ReadWrite`","line":1,"column":0,"stop_line":1,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_ReadWrite]` is an invalid taint annotation: Unsupported taint sink `FileSystem_ReadWrite`","line":2,"column":0,"stop_line":2,"stop_column":90,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_ReadWrite]` is an invalid taint annotation: Unsupported taint sink `FileSystem_ReadWrite`","line":4,"column":0,"stop_line":4,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":5,"column":0,"stop_line":5,"stop_column":132,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":9},{"description":"`TaintSink[(FileSystem_ReadWrite, ViaValueOf[(mode, WithTag[\"file-open-mode\"])])]` is an invalid taint annotation: Unsupported taint sink `FileSystem_ReadWrite`","line":7,"column":0,"stop_line":7,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":9},{"description":"`fabric.operations.get` is not part of the environment!","line":10,"column":0,"stop_line":10,"stop_column":121,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":6},{"description":"`fabric.operations.put` is not part of the environment!","line":11,"column":0,"stop_line":11,"stop_column":121,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":6},{"description":"`fabric.transfer.Transfer.get` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":118,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":6},{"description":"`fabric.transfer.Transfer.put` is not part of the environment!","line":15,"column":0,"stop_line":15,"stop_column":118,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":6},{"description":"`fabric2.transfer.Transfer.get` is not part of the environment!","line":18,"column":0,"stop_line":18,"stop_column":119,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":6},{"description":"`fabric2.transfer.Transfer.put` is not part of the environment!","line":19,"column":0,"stop_line":19,"stop_column":119,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/filesystem_sinks.pysa","code":6},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":94,"column":10,"stop_line":96,"stop_column":3,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Parameter)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":83,"column":10,"stop_line":86,"stop_column":3,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":3,"column":0,"stop_line":3,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":4,"column":0,"stop_line":4,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":5,"column":0,"stop_line":5,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":6,"column":0,"stop_line":6,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, Cookies)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":8,"column":1,"stop_line":9,"stop_column":113,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":10,"column":0,"stop_line":10,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":11,"column":0,"stop_line":11,"stop_column":105,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":12,"column":1,"stop_line":13,"stop_column":127,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":14,"column":1,"stop_line":15,"stop_column":135,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":16,"column":1,"stop_line":17,"stop_column":110,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":18,"column":0,"stop_line":18,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":20,"column":0,"stop_line":20,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":21,"column":0,"stop_line":21,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":22,"column":0,"stop_line":22,"stop_column":101,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":23,"column":1,"stop_line":24,"stop_column":104,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":25,"column":0,"stop_line":25,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":26,"column":0,"stop_line":26,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":27,"column":0,"stop_line":27,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":28,"column":0,"stop_line":28,"stop_column":141,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":29,"column":0,"stop_line":29,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[ResponseData]` is an invalid taint annotation: Unsupported taint source `ResponseData`","line":32,"column":0,"stop_line":32,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[URL]` is an invalid taint annotation: Unsupported taint source `URL`","line":33,"column":0,"stop_line":33,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSource[UserControlled]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":36,"column":0,"stop_line":36,"stop_column":56,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[Redirect]` is an invalid taint annotation: Unsupported taint sink `Redirect`","line":39,"column":0,"stop_line":39,"stop_column":79,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_ReadWrite]` is an invalid taint annotation: Unsupported taint sink `FileSystem_ReadWrite`","line":40,"column":0,"stop_line":49,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[(ReturnedToUser, ResponseHeaderName, ResponseHeaderValue)]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":51,"column":0,"stop_line":55,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[(ReturnedToUser, XSS)]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":56,"column":0,"stop_line":59,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":60,"column":0,"stop_line":64,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[(ReturnedToUser, XSS)]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":66,"column":0,"stop_line":66,"stop_column":75,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":67,"column":0,"stop_line":67,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":68,"column":0,"stop_line":71,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":72,"column":0,"stop_line":75,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/flask_sources_sinks.pysa","code":9},{"description":"`TaintSink[FormatString]` is an invalid taint annotation: Unsupported taint sink `FormatString`","line":1,"column":0,"stop_line":1,"stop_column":50,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/format_string_sinks.pysa","code":9},{"description":"`furl.PathCompositionInterface.__setattr__` is not part of the environment!","line":1,"column":0,"stop_line":1,"stop_column":117,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.QueryCompositionInterface.__setattr__` is not part of the environment!","line":2,"column":0,"stop_line":2,"stop_column":126,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.FragmentCompositionInterface.__setattr__` is not part of the environment!","line":3,"column":0,"stop_line":3,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.omdict1D.add` is not part of the environment!","line":5,"column":0,"stop_line":5,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.omdict1D.set` is not part of the environment!","line":6,"column":0,"stop_line":6,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.omdict1D.__setitem__` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.__init__` is not part of the environment!","line":9,"column":0,"stop_line":9,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.load` is not part of the environment!","line":10,"column":0,"stop_line":13,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.add` is not part of the environment!","line":14,"column":0,"stop_line":21,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.set` is not part of the environment!","line":22,"column":0,"stop_line":39,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.scheme` is not part of the environment!","line":41,"column":1,"stop_line":42,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.host` is not part of the environment!","line":43,"column":1,"stop_line":44,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.port` is not part of the environment!","line":45,"column":1,"stop_line":46,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.netloc` is not part of the environment!","line":47,"column":1,"stop_line":48,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.origin` is not part of the environment!","line":49,"column":1,"stop_line":50,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.furl.url` is not part of the environment!","line":51,"column":1,"stop_line":52,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.QueryCompositionInterface.query` is not part of the environment!","line":53,"column":1,"stop_line":54,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.QueryCompositionInterface.args` is not part of the environment!","line":55,"column":1,"stop_line":56,"stop_column":110,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`furl.PathCompositionInterface.path` is not part of the environment!","line":57,"column":1,"stop_line":58,"stop_column":101,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/furl_features.pysa","code":6},{"description":"`TaintInTaintOut[Via[string_concat_rhs]]` is an invalid taint annotation: Unrecognized Via annotation `string_concat_rhs`","line":2,"column":1,"stop_line":3,"stop_column":124,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":6,"column":0,"stop_line":6,"stop_column":74,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":7,"column":0,"stop_line":7,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":8,"column":0,"stop_line":8,"stop_column":70,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":9,"column":0,"stop_line":9,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":10,"column":0,"stop_line":10,"stop_column":75,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":11,"column":0,"stop_line":11,"stop_column":74,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":12,"column":0,"stop_line":12,"stop_column":70,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[XMLParser]` is an invalid taint annotation: Unsupported taint sink `XMLParser`","line":13,"column":0,"stop_line":13,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSink[GetAttr]` is an invalid taint annotation: Unsupported taint sink `GetAttr`","line":16,"column":1,"stop_line":21,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[Via[bytesio]]` is an invalid taint annotation: Unrecognized Via annotation `bytesio`","line":23,"column":1,"stop_line":24,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[Via[hmac_key]]` is an invalid taint annotation: Unrecognized Via annotation `hmac_key`","line":26,"column":1,"stop_line":27,"stop_column":70,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[(LocalReturn, Via[benign])]` is an invalid taint annotation: Unrecognized Via annotation `benign`","line":29,"column":1,"stop_line":30,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[Via[benign]]` is an invalid taint annotation: Unrecognized Via annotation `benign`","line":32,"column":1,"stop_line":34,"stop_column":61,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[Via[benign]]` is an invalid taint annotation: Unrecognized Via annotation `benign`","line":35,"column":0,"stop_line":35,"stop_column":50,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[Via[benign]]` is an invalid taint annotation: Unrecognized Via annotation `benign`","line":36,"column":0,"stop_line":36,"stop_column":49,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintInTaintOut[(LocalReturn, Via[urllib_quote_plus])]` is an invalid taint annotation: Unrecognized Via annotation `urllib_quote_plus`","line":40,"column":1,"stop_line":41,"stop_column":118,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSource[(ExceptionMessage, ViaTypeOf[self])]` is an invalid taint annotation: Unsupported taint source `ExceptionMessage`","line":44,"column":0,"stop_line":44,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSource[(ExceptionMessage, ViaTypeOf[self])]` is an invalid taint annotation: Unsupported taint source `ExceptionMessage`","line":45,"column":0,"stop_line":45,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSource[CLIUserControlled]` is an invalid taint annotation: Unsupported taint source `CLIUserControlled`","line":48,"column":0,"stop_line":48,"stop_column":79,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/general.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":2,"column":0,"stop_line":2,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":3,"column":0,"stop_line":3,"stop_column":94,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":6,"column":0,"stop_line":6,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":7,"column":0,"stop_line":7,"stop_column":68,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSource[(UserControlled, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":9,"column":0,"stop_line":9,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSource[(UserControlled, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":10,"column":0,"stop_line":10,"stop_column":73,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSource[(UserControlled, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":11,"column":0,"stop_line":11,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":12,"column":0,"stop_line":12,"stop_column":165,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":13,"column":0,"stop_line":13,"stop_column":132,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[(ReturnedToUser, ResponseHeaderValue)]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":14,"column":0,"stop_line":14,"stop_column":172,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":15,"column":0,"stop_line":15,"stop_column":137,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/http_server.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":3,"column":0,"stop_line":3,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":7,"column":0,"stop_line":14,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":16,"column":0,"stop_line":23,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":25,"column":0,"stop_line":32,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":34,"column":0,"stop_line":41,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":43,"column":0,"stop_line":50,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":52,"column":0,"stop_line":59,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":61,"column":0,"stop_line":69,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":73,"column":0,"stop_line":79,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":81,"column":0,"stop_line":87,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":89,"column":0,"stop_line":95,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":97,"column":0,"stop_line":103,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":105,"column":0,"stop_line":111,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":113,"column":0,"stop_line":119,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":121,"column":0,"stop_line":127,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":129,"column":0,"stop_line":136,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":140,"column":0,"stop_line":147,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":149,"column":0,"stop_line":156,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":158,"column":0,"stop_line":165,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":167,"column":0,"stop_line":174,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":176,"column":0,"stop_line":183,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":185,"column":0,"stop_line":192,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":194,"column":0,"stop_line":201,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":203,"column":0,"stop_line":211,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/logging_sinks.pysa","code":9},{"description":"`lxml.etree.fromstring` is not part of the environment!","line":1,"column":0,"stop_line":1,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/lxml_sinks.pysa","code":6},{"description":"`lxml.etree.parse` is not part of the environment!","line":2,"column":0,"stop_line":2,"stop_column":55,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/lxml_sinks.pysa","code":6},{"description":"`lxml.etree.fromstringlist` is not part of the environment!","line":3,"column":0,"stop_line":3,"stop_column":65,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/lxml_sinks.pysa","code":6},{"description":"`mysql.connector.abstracts.MySQLCursorAbstract.execute` is not part of the environment!","line":1,"column":0,"stop_line":1,"stop_column":110,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.abstracts.MySQLCursorAbstract.executemany` is not part of the environment!","line":2,"column":0,"stop_line":2,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.abstracts.MySQLConnectionAbstract.cmd_query` is not part of the environment!","line":4,"column":0,"stop_line":4,"stop_column":127,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.abstracts.MySQLConnectionAbstract.cmd_query_iter` is not part of the environment!","line":5,"column":0,"stop_line":5,"stop_column":107,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.abstracts.MySQLConnectionAbstract.info_query` is not part of the environment!","line":6,"column":0,"stop_line":6,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.abstracts.MySQLConnectionAbstract.cmd_stmt_prepare` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.connection.MySQLConnection.cmd_query` is not part of the environment!","line":9,"column":0,"stop_line":9,"stop_column":120,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.connection.MySQLConnection.cmd_query_iter` is not part of the environment!","line":10,"column":0,"stop_line":10,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.connection.MySQLConnection.info_query` is not part of the environment!","line":11,"column":0,"stop_line":11,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.connection.MySQLConnection.cmd_stmt_prepare` is not part of the environment!","line":12,"column":0,"stop_line":12,"stop_column":101,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.connection_cext.CMySQLConnection.cmd_query` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":126,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`mysql.connector.connection_cext.CMySQLConnection.info_query` is not part of the environment!","line":15,"column":0,"stop_line":15,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysql_connector_sinks.pysa","code":6},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":1,"column":0,"stop_line":1,"stop_column":77,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysqldb_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":2,"column":0,"stop_line":2,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysqldb_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":3,"column":0,"stop_line":3,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/mysqldb_sinks.pysa","code":9},{"description":"`pandas.core.computation.eval.eval` is not part of the environment!","line":1,"column":0,"stop_line":1,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.pickle.read_pickle` is not part of the environment!","line":2,"column":0,"stop_line":2,"stop_column":141,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.sql.read_sql` is not part of the environment!","line":4,"column":0,"stop_line":4,"stop_column":57,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.sql.read_sql_query` is not part of the environment!","line":5,"column":0,"stop_line":5,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.parsers.read_csv` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":105,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.json._json.read_json` is not part of the environment!","line":8,"column":0,"stop_line":8,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.html.read_html` is not part of the environment!","line":9,"column":0,"stop_line":9,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.excel._base.read_excel` is not part of the environment!","line":10,"column":0,"stop_line":10,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.pytables.read_hdf` is not part of the environment!","line":11,"column":0,"stop_line":11,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.parquet.read_parquet` is not part of the environment!","line":12,"column":0,"stop_line":12,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.feather_format.read_feather` is not part of the environment!","line":13,"column":0,"stop_line":13,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.orc.read_orc` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.io.spss.read_spss` is not part of the environment!","line":15,"column":0,"stop_line":15,"stop_column":72,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.core.generic.NDFrame.to_csv` is not part of the environment!","line":17,"column":0,"stop_line":17,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.core.generic.NDFrame.to_hdf` is not part of the environment!","line":18,"column":0,"stop_line":18,"stop_column":100,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.core.generic.NDFrame.to_latex` is not part of the environment!","line":19,"column":0,"stop_line":19,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`pandas.core.generic.NDFrame.to_sql` is not part of the environment!","line":20,"column":0,"stop_line":20,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pandas_sinks.pysa","code":6},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":1,"column":0,"stop_line":1,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/psycopg2_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":2,"column":0,"stop_line":2,"stop_column":68,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/psycopg2_sinks.pysa","code":9},{"description":"`pymssql.Cursor.execute` is not part of the environment!","line":1,"column":0,"stop_line":1,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pymssql_sinks.pysa","code":6},{"description":"`pymssql.Cursor.executemany` is not part of the environment!","line":2,"column":0,"stop_line":2,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pymssql_sinks.pysa","code":6},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":1,"column":0,"stop_line":1,"stop_column":62,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pymysql_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":2,"column":0,"stop_line":2,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/pymysql_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":2,"column":0,"stop_line":2,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":3,"column":0,"stop_line":3,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecImportSink]` is an invalid taint annotation: Unsupported taint sink `ExecImportSink`","line":4,"column":0,"stop_line":4,"stop_column":74,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecImportSink]` is an invalid taint annotation: Unsupported taint sink `ExecImportSink`","line":5,"column":0,"stop_line":11,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":12,"column":0,"stop_line":20,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":21,"column":0,"stop_line":28,"stop_column":8,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":29,"column":0,"stop_line":35,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":36,"column":0,"stop_line":39,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":40,"column":0,"stop_line":40,"stop_column":74,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":42,"column":0,"stop_line":68,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":70,"column":0,"stop_line":89,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":91,"column":0,"stop_line":110,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":112,"column":0,"stop_line":135,"stop_column":7,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[(RemoteCodeExecution, ViaTypeOf[cmd])]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":137,"column":0,"stop_line":137,"stop_column":88,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[(RemoteCodeExecution, ViaTypeOf[cmd])]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":139,"column":0,"stop_line":139,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":141,"column":0,"stop_line":147,"stop_column":52,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":150,"column":0,"stop_line":174,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":176,"column":0,"stop_line":199,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":201,"column":0,"stop_line":201,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":202,"column":0,"stop_line":202,"stop_column":132,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":206,"column":0,"stop_line":206,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":207,"column":0,"stop_line":207,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":208,"column":0,"stop_line":208,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":209,"column":0,"stop_line":209,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":210,"column":0,"stop_line":210,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":211,"column":0,"stop_line":211,"stop_column":107,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":212,"column":0,"stop_line":212,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":213,"column":0,"stop_line":213,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":214,"column":0,"stop_line":214,"stop_column":70,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":215,"column":0,"stop_line":215,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":216,"column":0,"stop_line":216,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":217,"column":0,"stop_line":217,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":218,"column":0,"stop_line":218,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":219,"column":0,"stop_line":219,"stop_column":84,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":220,"column":0,"stop_line":220,"stop_column":114,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecArgSink]` is an invalid taint annotation: Unsupported taint sink `ExecArgSink`","line":221,"column":0,"stop_line":221,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecEnvSink]` is an invalid taint annotation: Unsupported taint sink `ExecEnvSink`","line":222,"column":0,"stop_line":222,"stop_column":109,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":223,"column":0,"stop_line":223,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":226,"column":0,"stop_line":226,"stop_column":67,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[FileSystem_Other]` is an invalid taint annotation: Unsupported taint sink `FileSystem_Other`","line":227,"column":0,"stop_line":227,"stop_column":58,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[ExecDeserializationSink]` is an invalid taint annotation: Unsupported taint sink `ExecDeserializationSink`","line":230,"column":0,"stop_line":230,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[shell_escape]]` is an invalid taint annotation: Unrecognized Via annotation `shell_escape`","line":233,"column":1,"stop_line":234,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":237,"column":0,"stop_line":237,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":238,"column":0,"stop_line":238,"stop_column":128,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":239,"column":0,"stop_line":239,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RemoteCodeExecution]` is an invalid taint annotation: Unsupported taint sink `RemoteCodeExecution`","line":240,"column":0,"stop_line":240,"stop_column":75,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/rce_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":2,"column":0,"stop_line":19,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":20,"column":0,"stop_line":36,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":37,"column":0,"stop_line":53,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":54,"column":0,"stop_line":70,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_METADATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_METADATA`","line":71,"column":0,"stop_line":87,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":88,"column":0,"stop_line":104,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":105,"column":0,"stop_line":121,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":122,"column":0,"stop_line":138,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":141,"column":0,"stop_line":158,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":159,"column":0,"stop_line":176,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":177,"column":0,"stop_line":194,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_METADATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_METADATA`","line":195,"column":0,"stop_line":212,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":213,"column":0,"stop_line":230,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":231,"column":0,"stop_line":248,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":249,"column":0,"stop_line":266,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":267,"column":0,"stop_line":285,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[Authentication]` is an invalid taint annotation: Unsupported taint sink `Authentication`","line":288,"column":0,"stop_line":288,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[Authentication]` is an invalid taint annotation: Unsupported taint sink `Authentication`","line":289,"column":0,"stop_line":289,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":292,"column":0,"stop_line":294,"stop_column":51,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":295,"column":0,"stop_line":295,"stop_column":126,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":296,"column":0,"stop_line":296,"stop_column":117,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":297,"column":0,"stop_line":297,"stop_column":124,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":298,"column":0,"stop_line":298,"stop_column":138,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[urlencode]]` is an invalid taint annotation: Unrecognized Via annotation `urlencode`","line":299,"column":1,"stop_line":300,"stop_column":113,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[urlencode]]` is an invalid taint annotation: Unrecognized Via annotation `urlencode`","line":301,"column":1,"stop_line":302,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[urlencode]]` is an invalid taint annotation: Unrecognized Via annotation `urlencode`","line":303,"column":1,"stop_line":304,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_METADATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_METADATA`","line":307,"column":0,"stop_line":313,"stop_column":45,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_METADATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_METADATA`","line":314,"column":0,"stop_line":324,"stop_column":46,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_METADATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_METADATA`","line":325,"column":0,"stop_line":332,"stop_column":44,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_METADATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_METADATA`","line":333,"column":0,"stop_line":337,"stop_column":47,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_URI]` is an invalid taint annotation: Unsupported taint sink `RequestSend_URI`","line":338,"column":0,"stop_line":343,"stop_column":47,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":344,"column":0,"stop_line":347,"stop_column":46,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_URI]` is an invalid taint annotation: Unsupported taint sink `RequestSend_URI`","line":350,"column":0,"stop_line":350,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_URI]` is an invalid taint annotation: Unsupported taint sink `RequestSend_URI`","line":351,"column":0,"stop_line":351,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_URI]` is an invalid taint annotation: Unsupported taint sink `RequestSend_URI`","line":352,"column":0,"stop_line":352,"stop_column":79,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":353,"column":0,"stop_line":353,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[RequestSend_DATA]` is an invalid taint annotation: Unsupported taint sink `RequestSend_DATA`","line":354,"column":0,"stop_line":354,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[(RequestSend_URI, RequestSend_METADATA, RequestSend_DATA, ViaValueOf[option])]` is an invalid taint annotation: Unsupported taint sink `RequestSend_URI`","line":357,"column":0,"stop_line":357,"stop_column":136,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/requests_api_sinks.pysa","code":9},{"description":"`TaintSink[ServerSideTemplateInjection]` is an invalid taint annotation: Unsupported taint sink `ServerSideTemplateInjection`","line":2,"column":0,"stop_line":2,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/server_side_template_injection_sinks.pysa","code":9},{"description":"`TaintSink[(ServerSideTemplateInjection, ViaTypeOf[self])]` is an invalid taint annotation: Unsupported taint sink `ServerSideTemplateInjection`","line":3,"column":0,"stop_line":3,"stop_column":122,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/server_side_template_injection_sinks.pysa","code":9},{"description":"`TaintSink[(ServerSideTemplateInjection, ViaTypeOf[self])]` is an invalid taint annotation: Unsupported taint sink `ServerSideTemplateInjection`","line":4,"column":0,"stop_line":4,"stop_column":129,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/server_side_template_injection_sinks.pysa","code":9},{"description":"`django.template.engine.Engine.from_string` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":98,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/server_side_template_injection_sinks.pysa","code":6},{"description":"`django.template.base.Template.__init__` is not part of the environment!","line":8,"column":0,"stop_line":8,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/server_side_template_injection_sinks.pysa","code":6},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":1,"column":0,"stop_line":1,"stop_column":153,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":2,"column":0,"stop_line":2,"stop_column":101,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":3,"column":0,"stop_line":3,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":9},{"description":"Model signature parameters for `sqlalchemy.engine.base.Connection.execute` do not match implementation `(self: Connection, object_: unknown, *(unknown), **(unknown)) -> Any`. Reason: unexpected positional parameter: `object`.","line":4,"column":0,"stop_line":4,"stop_column":104,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":2},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":5,"column":0,"stop_line":5,"stop_column":105,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":9},{"description":"Model signature parameters for `sqlalchemy.engine.base.Connection.scalar` do not match implementation `(self: Connection, object_: unknown, *(unknown), **(unknown)) -> Any`. Reason: unexpected positional parameter: `object`.","line":6,"column":0,"stop_line":6,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":2},{"description":"Model signature parameters for `sqlalchemy.engine.interfaces.Connectable.execute` do not match implementation `(self: Connectable, object_: unknown, *(unknown), **(unknown)) -> Any`. Reason: unexpected positional parameter: `object`.","line":7,"column":0,"stop_line":7,"stop_column":111,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":2},{"description":"Model signature parameters for `sqlalchemy.engine.interfaces.Connectable.scalar` do not match implementation `(self: Connectable, object_: unknown, *(unknown), **(unknown)) -> Any`. Reason: unexpected positional parameter: `object`.","line":8,"column":0,"stop_line":8,"stop_column":110,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlalchemy_sinks.pysa","code":2},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":1,"column":0,"stop_line":1,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlite3_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":2,"column":0,"stop_line":2,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlite3_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":3,"column":0,"stop_line":3,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlite3_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":4,"column":0,"stop_line":4,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlite3_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":5,"column":0,"stop_line":5,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlite3_sinks.pysa","code":9},{"description":"`TaintSink[SQL]` is an invalid taint annotation: Unsupported taint sink `SQL`","line":6,"column":0,"stop_line":6,"stop_column":84,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/sqlite3_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Parameter)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":63,"column":10,"stop_line":68,"stop_column":3,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":9},{"description":"`tornado.web.RequestHandler.get_argument` is not part of the environment!","line":1,"column":0,"stop_line":6,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.get_arguments` is not part of the environment!","line":7,"column":0,"stop_line":7,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.get_body_argument` is not part of the environment!","line":8,"column":0,"stop_line":13,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.get_body_arguments` is not part of the environment!","line":14,"column":0,"stop_line":14,"stop_column":130,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.get_query_argument` is not part of the environment!","line":15,"column":0,"stop_line":20,"stop_column":63,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.get_query_arguments` is not part of the environment!","line":21,"column":0,"stop_line":21,"stop_column":131,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.write` is not part of the environment!","line":23,"column":0,"stop_line":23,"stop_column":81,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.set_header` is not part of the environment!","line":25,"column":0,"stop_line":25,"stop_column":146,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.add_header` is not part of the environment!","line":26,"column":0,"stop_line":26,"stop_column":146,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.redirect` is not part of the environment!","line":28,"column":0,"stop_line":28,"stop_column":95,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.path_args` is not part of the environment!","line":30,"column":0,"stop_line":30,"stop_column":89,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.web.RequestHandler.path_kwargs` is not part of the environment!","line":31,"column":0,"stop_line":31,"stop_column":91,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.path` is not part of the environment!","line":33,"column":0,"stop_line":33,"stop_column":57,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.uri` is not part of the environment!","line":34,"column":0,"stop_line":34,"stop_column":56,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.headers` is not part of the environment!","line":36,"column":0,"stop_line":36,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.cookies` is not part of the environment!","line":38,"column":1,"stop_line":39,"stop_column":118,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.files` is not part of the environment!","line":41,"column":0,"stop_line":41,"stop_column":113,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.query` is not part of the environment!","line":43,"column":0,"stop_line":43,"stop_column":93,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.body` is not part of the environment!","line":44,"column":0,"stop_line":44,"stop_column":92,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.arguments` is not part of the environment!","line":45,"column":0,"stop_line":45,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.query_arguments` is not part of the environment!","line":46,"column":0,"stop_line":46,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`tornado.httputil.HTTPServerRequest.body_arguments` is not part of the environment!","line":47,"column":0,"stop_line":47,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/tornado_sources_sinks.pysa","code":6},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":2,"column":0,"stop_line":7,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`django.core.mail.send_mail` is not part of the environment!","line":9,"column":0,"stop_line":15,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":6},{"description":"`django.core.mail.message.EmailMessage.__init__` is not part of the environment!","line":16,"column":0,"stop_line":28,"stop_column":6,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":6},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":30,"column":0,"stop_line":30,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":31,"column":0,"stop_line":31,"stop_column":58,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":33,"column":0,"stop_line":33,"stop_column":65,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":34,"column":0,"stop_line":34,"stop_column":71,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":35,"column":0,"stop_line":35,"stop_column":72,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":36,"column":0,"stop_line":36,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":38,"column":0,"stop_line":38,"stop_column":58,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":39,"column":0,"stop_line":39,"stop_column":58,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":41,"column":0,"stop_line":41,"stop_column":75,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":42,"column":0,"stop_line":42,"stop_column":68,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":43,"column":0,"stop_line":43,"stop_column":73,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":44,"column":0,"stop_line":44,"stop_column":97,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":45,"column":0,"stop_line":45,"stop_column":133,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":46,"column":0,"stop_line":46,"stop_column":104,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":47,"column":0,"stop_line":47,"stop_column":134,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":49,"column":0,"stop_line":49,"stop_column":72,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":50,"column":0,"stop_line":50,"stop_column":72,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":51,"column":0,"stop_line":51,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":52,"column":0,"stop_line":52,"stop_column":75,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":54,"column":0,"stop_line":54,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":56,"column":0,"stop_line":56,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":57,"column":0,"stop_line":57,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":58,"column":0,"stop_line":58,"stop_column":78,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":59,"column":0,"stop_line":59,"stop_column":76,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSink[EmailSend]` is an invalid taint annotation: Unsupported taint sink `EmailSend`","line":60,"column":0,"stop_line":60,"stop_column":71,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/user_reach_sinks.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":2,"column":0,"stop_line":2,"stop_column":99,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":3,"column":0,"stop_line":3,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, URL)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":4,"column":0,"stop_line":4,"stop_column":103,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ResponseHeaderValue]` is an invalid taint annotation: Unsupported taint sink `ResponseHeaderValue`","line":7,"column":0,"stop_line":7,"stop_column":124,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":8,"column":0,"stop_line":8,"stop_column":120,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":9,"column":0,"stop_line":9,"stop_column":116,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":10,"column":0,"stop_line":10,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":11,"column":0,"stop_line":11,"stop_column":109,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":12,"column":0,"stop_line":12,"stop_column":108,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":13,"column":0,"stop_line":13,"stop_column":112,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ResponseHeaderValue]` is an invalid taint annotation: Unsupported taint sink `ResponseHeaderValue`","line":14,"column":0,"stop_line":14,"stop_column":125,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ResponseHeaderValue]` is an invalid taint annotation: Unsupported taint sink `ResponseHeaderValue`","line":15,"column":0,"stop_line":15,"stop_column":138,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":18,"column":0,"stop_line":18,"stop_column":131,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Meta, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":21,"column":0,"stop_line":21,"stop_column":104,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[(ResponseHeaderName, ResponseHeaderValue, ReturnedToUser)]` is an invalid taint annotation: Unsupported taint sink `ResponseHeaderName`","line":23,"column":0,"stop_line":23,"stop_column":110,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":24,"column":0,"stop_line":24,"stop_column":66,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[(ResponseHeaderName, ResponseHeaderValue, ReturnedToUser)]` is an invalid taint annotation: Unsupported taint sink `ResponseHeaderName`","line":25,"column":0,"stop_line":27,"stop_column":35,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":28,"column":0,"stop_line":28,"stop_column":82,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[Logging]` is an invalid taint annotation: Unsupported taint sink `Logging`","line":29,"column":0,"stop_line":29,"stop_column":87,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[(ResponseHeaderName, ResponseHeaderValue, ReturnedToUser)]` is an invalid taint annotation: Unsupported taint sink `ResponseHeaderName`","line":30,"column":0,"stop_line":30,"stop_column":178,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":32,"column":0,"stop_line":32,"stop_column":101,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":33,"column":0,"stop_line":33,"stop_column":64,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":34,"column":0,"stop_line":34,"stop_column":102,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":35,"column":0,"stop_line":35,"stop_column":122,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Payload, HeaderData)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":36,"column":0,"stop_line":36,"stop_column":123,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSink[ReturnedToUser]` is an invalid taint annotation: Unsupported taint sink `ReturnedToUser`","line":37,"column":0,"stop_line":37,"stop_column":85,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wsgi_ref.pysa","code":9},{"description":"`TaintSource[(UserControlled, UserControlled_Parameter)]` is an invalid taint annotation: Unsupported taint source `UserControlled`","line":9,"column":10,"stop_line":13,"stop_column":3,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/wtforms_sources.pysa","code":9},{"description":"`TaintSink[XSS]` is an invalid taint annotation: Unsupported taint sink `XSS`","line":2,"column":0,"stop_line":2,"stop_column":59,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintSink[XSS]` is an invalid taint annotation: Unsupported taint sink `XSS`","line":5,"column":0,"stop_line":5,"stop_column":80,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[escape_html]]` is an invalid taint annotation: Unrecognized Via annotation `escape_html`","line":6,"column":1,"stop_line":7,"stop_column":72,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintInTaintOut[(LocalReturn, Via[escape_html])]` is an invalid taint annotation: Unrecognized Via annotation `escape_html`","line":10,"column":1,"stop_line":11,"stop_column":84,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintSink[XSS]` is an invalid taint annotation: Unsupported taint sink `XSS`","line":14,"column":0,"stop_line":14,"stop_column":53,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintSink[XSS]` is an invalid taint annotation: Unsupported taint sink `XSS`","line":15,"column":0,"stop_line":15,"stop_column":62,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintSink[XSS]` is an invalid taint annotation: Unsupported taint sink `XSS`","line":16,"column":0,"stop_line":16,"stop_column":69,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintSink[XSS]` is an invalid taint annotation: Unsupported taint sink `XSS`","line":17,"column":0,"stop_line":17,"stop_column":90,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[escape_html]]` is an invalid taint annotation: Unrecognized Via annotation `escape_html`","line":20,"column":1,"stop_line":21,"stop_column":86,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9},{"description":"`TaintInTaintOut[Via[escape_html]]` is an invalid taint annotation: Unrecognized Via annotation `escape_html`","line":22,"column":1,"stop_line":23,"stop_column":83,"path":"/home/sampath/mis/fact-bounty/env/pysa/lib/pyre_check/taint/xss_sinks.pysa","code":9}]},"codes":{}}